[package]
name = "quickfetch-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30.13"
local-ip-address = "0.6.5"
whoami = "1.6.0"
clap = { version = "4.5", features = ["derive"] }

[[bin]]
name = "quickfetch-rust"
path = "main.rs"